"""HM3D/Matterport-oriented labels for GroundingDINO and semantic validation."""

HM3D_DINO_PROMPT_LABELS = [
    "chair",
    "armchair",
    "sofa",
    "bed",
    "table",
    "desk",
    "cabinet",
    "shelf",
    "bookshelf",
    "dresser",
    "chest of drawers",
    "wardrobe",
    "counter",
    "sink",
    "toilet",
    "bathtub",
    "shower",
    "mirror",
    "picture",
    "tv",
    "cushion",
    "pillow",
    "curtain",
    "blinds",
    "towel",
    "stool",
    "bench",
    "lamp",
    "fireplace",
    "refrigerator",
    "microwave",
    "oven",
    "plant",
]

HM3D_DINO_PROMPT = " . ".join(HM3D_DINO_PROMPT_LABELS) + " ."

HM3D_CANONICAL_LABELS = {
    "Appliance",
    "Bathtub",
    "Beam",
    "Bed",
    "Bench",
    "Blinds",
    "BoardPanel",
    "Cabinet",
    "Ceiling",
    "Chair",
    "Clothes",
    "Column",
    "Counter",
    "Cushion",
    "Curtain",
    "Door",
    "Dresser",
    "Fireplace",
    "Floor",
    "Furniture",
    "GymEquipment",
    "Lamp",
    "Mirror",
    "Microwave",
    "Oven",
    "Picture",
    "Pillow",
    "Plant",
    "Railing",
    "Refrigerator",
    "Shelf",
    "Shower",
    "Sink",
    "Sofa",
    "Stairs",
    "Stool",
    "Table",
    "Toilet",
    "Towel",
    "TV",
    "Wall",
    "Wardrobe",
    "Window",
}

HM3D_LABEL_ALIASES = {
    "appliance": "Appliance",
    "appliances": "Appliance",
    "armchair": "Chair",
    "bath": "Bathtub",
    "bathtub": "Bathtub",
    "beam": "Beam",
    "bed": "Bed",
    "bench": "Bench",
    "blinds": "Blinds",
    "board": "BoardPanel",
    "board panel": "BoardPanel",
    "cabinet": "Cabinet",
    "ceiling": "Ceiling",
    "chair": "Chair",
    "chest of drawers": "Dresser",
    "closet": "Wardrobe",
    "clothes": "Clothes",
    "clothing": "Clothes",
    "column": "Column",
    "counter": "Counter",
    "countertop": "Counter",
    "counter top": "Counter",
    "cushion": "Cushion",
    "curtain": "Curtain",
    "curtains": "Curtain",
    "desk": "Table",
    "dining table": "Table",
    "door": "Door",
    "dresser": "Dresser",
    "fireplace": "Fireplace",
    "floor": "Floor",
    "furniture": "Furniture",
    "gym equipment": "GymEquipment",
    "lamp": "Lamp",
    "light": "Lamp",
    "lighting": "Lamp",
    "mirror": "Mirror",
    "microwave": "Microwave",
    "oven": "Oven",
    "painting": "Picture",
    "panel": "BoardPanel",
    "photo": "Picture",
    "picture": "Picture",
    "pillow": "Pillow",
    "plant": "Plant",
    "potted plant": "Plant",
    "railing": "Railing",
    "refrigerator": "Refrigerator",
    "fridge": "Refrigerator",
    "shelf": "Shelf",
    "shelves": "Shelf",
    "shelving": "Shelf",
    "shelving unit": "Shelf",
    "bookshelf": "Shelf",
    "bookcase": "Shelf",
    "shower": "Shower",
    "sink": "Sink",
    "basin": "Sink",
    "sink basin": "Sink",
    "sofa": "Sofa",
    "couch": "Sofa",
    "stairs": "Stairs",
    "stair": "Stairs",
    "staircase": "Stairs",
    "stool": "Stool",
    "table": "Table",
    "side table": "Table",
    "coffee table": "Table",
    "toilet": "Toilet",
    "towel": "Towel",
    "tv": "TV",
    "television": "TV",
    "tv monitor": "TV",
    "monitor": "TV",
    "wall": "Wall",
    "wardrobe": "Wardrobe",
    "window": "Window",
}

for _label in HM3D_CANONICAL_LABELS:
    HM3D_LABEL_ALIASES.setdefault(_label, _label)

HM3D_COMPATIBLE_LABEL_GROUPS = [
    {"Chair", "Stool", "Bench"},
    {"Chair", "Sofa"},
    {"Table", "Counter"},
    {"Cabinet", "Shelf", "Wardrobe", "Dresser"},
    {"Shelf", "Cabinet"},
    {"Sink", "Bathtub", "Shower"},
    {"Lamp", "Appliance"},
    {"TV", "Picture", "BoardPanel"},
    {"Cushion", "Pillow"},
    {"Curtain", "Blinds"},
]

HM3D_REWARD_EXCLUDED_LABELS = {
    "Wall",
    "Floor",
    "Ceiling",
    "Window",
    "Door",
    "Stairs",
    "Column",
    "Beam",
    "Railing",
}
